fix: load AWS config and assume role
vmware-tanzu/velero-plugin-for-aws pull request #168
Opened 2023-08-02 12:15 UTC by luisdavim

This fixes https://github.com/vmware-tanzu/velero/issues/3142

2023-08-07 14:20 UTC, reasonerjt requested changes
I see an error when I patch the plugin with this change and test with IRSA

```
...
sg="Error getting backup store for this location" backupLocation=velero/default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: User: arn:aws:sts::822276436757:assumed-role/eksctl-jt-velero-irsa-addon-iamserviceaccoun-Role1-1T470KOHYLTBK/1691417499559809485 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::822276436757:role/eksctl-jt-velero-irsa-addon-iamserviceaccoun-Role1-1T470KOHYLTBK\n\tstatus code: 403, request id: 9e390336-c55f-4dd0-9d34-ec8233945ab6" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:67" error.function=main.getSession logSource="pkg/controller/backup_sync_controller.go:100"
```

2023-08-07 16:49 UTC, luisdavim commented
> I see an error when I patch the plugin with this change and test with IRSA
> 
> ```
> ...
> sg="Error getting backup store for this location" backupLocation=velero/default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: User: arn:aws:sts::822276436757:assumed-role/eksctl-jt-velero-irsa-addon-iamserviceaccoun-Role1-1T470KOHYLTBK/1691417499559809485 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::822276436757:role/eksctl-jt-velero-irsa-addon-iamserviceaccoun-Role1-1T470KOHYLTBK\n\tstatus code: 403, request id: 9e390336-c55f-4dd0-9d34-ec8233945ab6" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:67" error.function=main.getSession logSource="pkg/controller/backup_sync_controller.go:100"
> ```

That looks like the role is being assumed twice, I guess the SDK is handling that for us now and the extra assume role is not needed, I've updated the PR, can you run that test again? Thanks.

2023-08-08 06:49 UTC, reasonerjt approved these changes

2023-08-09 03:29 UTC, blackpiglet approved these changes

2023-08-09 03:30 UTC, merged