remove ashish-amarnath from maintainers
vmware-tanzu/velero-plugin-for-aws pull request #78
Opened 2021-06-02 20:38 UTC by ashish-amarnath

Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

2021-06-03 14:59 UTC, dsu-igeek approved these changes
Thanks!

2021-06-03 15:06 UTC, zubron commented on osstp.yaml
> +other:velero-plugin-for-aws:v1.1.0:
This file should be removed from this PR.

2021-06-03 15:08 UTC, zubron requested changes
Thanks for everything, @ashish-amarnath! There is just an extra file in this PR that I don't think should have been included.

2021-06-07 16:34 UTC, zubron approved these changes
Thanks, @ashish-amarnath!

2021-06-07 17:33 UTC, dsu-igeek approved these changes
Thanks Ashish!

2021-06-07 17:33 UTC, merged